name: Hello GitHub Actions

on:
  push:
  pull_request:
  workflow_dispatch:


env:
  APP_NAME: git-learning
  ENVIRONMENT: dev

jobs:
  hello:
    runs-on: ubuntu-latest

    env:
      VERSION: "1.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show files
        run: ls -la

      - name: System information
        run: |
          pwd
          ls -la
          echo "GitHub Actions is running"

      - name: Show environment variables
        run: |
          echo "Application: $APP_NAME"
          echo "Environment: $ENVIRONMENT"    

      - name: Show job variable
        run: echo "Version:$VERSION"    

      - name: Test secret
        run: echo "Secret is ${{ secrets.DEMO_SECRET }}"  